      FUNCTION DF1DIM(X)
      PARAMETER (NMAX=50)
      COMMON /F1COM/ NCOM,PCOM(NMAX),XICOM(NMAX)
      DIMENSION XT(NMAX),DF(NMAX)
      DO 11 J=1,NCOM
        XT(J)=PCOM(J)+X*XICOM(J)
11    CONTINUE
      CALL DFUNC(XT,DF)
      DF1DIM=0.
      DO 12 J=1,NCOM
        DF1DIM=DF1DIM+DF(J)*XICOM(J)
12    CONTINUE
      RETURN
      END
