      DOUBLE PRECISION FUNCTION DGAMMP(A,X)
      DOUBLE PRECISION A,X,GAMSER,GAMMCF,GLN
      IF(X.LT.0..OR.A.LE.0.)PAUSE
      IF(X.LT.A+1.)THEN
        CALL DGSER(GAMSER,A,X,GLN)
        DGAMMP=GAMSER
      ELSE
        CALL DGCF(GAMMCF,A,X,GLN)
        DGAMMP=1.-GAMMCF
      ENDIF
      RETURN
      END
