      FUNCTION EVLMEM(FDT,COF,M,PM)
      DIMENSION COF(M)
      REAL*8 WR,WI,WPR,WPI,WTEMP,THETA
      THETA=6.28318530717959D0*FDT
      WPR=DCOS(THETA)
      WPI=DSIN(THETA)
      WR=1.D0
      WI=0.D0
      SUMR=1.
      SUMI=0.
      DO 11 I=1,M
        WTEMP=WR
        WR=WR*WPR-WI*WPI
        WI=WI*WPR+WTEMP*WPI
        SUMR=SUMR-COF(I)*SNGL(WR)
        SUMI=SUMI-COF(I)*SNGL(WI)
11    CONTINUE
      EVLMEM=PM/(SUMR**2+SUMI**2)
      RETURN
      END
