      FUNCTION IRBIT2(ISEED)
      PARAMETER (IB1=1,IB2=2,IB5=16,IB18=131072,MASK=IB1+IB2+IB5)
      IF(IAND(ISEED,IB18).NE.0)THEN
        ISEED=IOR(ISHFT(IEOR(ISEED,MASK),1),IB1)
        IRBIT2=1
      ELSE
        ISEED=IAND(ISHFT(ISEED,1),NOT(IB1))
        IRBIT2=0
      ENDIF
      RETURN
      END
