      SUBROUTINE PREDIC(DATA,NDATA,D,NPOLES,FUTURE,NFUT)
      PARAMETER (NPMAX=100)
      DIMENSION DATA(NDATA),D(NPOLES),FUTURE(NFUT),REG(NPMAX)
      DO 11 J=1,NPOLES
        REG(J)=DATA(NDATA+1-J)
11    CONTINUE
      DO 14 J=1,NFUT
        DISCRP=0.
        SUM=DISCRP
        DO 12 K=1,NPOLES
          SUM=SUM+D(K)*REG(K)
12      CONTINUE
        DO 13 K=NPOLES,2,-1
          REG(K)=REG(K-1)
13      CONTINUE
        REG(1)=SUM
        FUTURE(J)=SUM
14    CONTINUE
      RETURN
      END
