#! /bin/tcsh -f

echo 'Compiling libraries...'

cd $RADSRC/rtm_util
make clean
touch *.f
make lib

cd $RADSRC/spec_data
make clean
touch *.f
make lib

cd $RADSRC/path
make clean
touch *.f
make lib

cd $RADSRC/scatter
make clean
touch *.f
make lib

cd $RADSRC/radtran
make clean
touch *.f
make lib

cd $RADSRC/ciatable
make clean
touch *.f
make lib

cd $RADSRC/cirsrad
make clean
touch *.f
make lib

cd $RADSRC/cirsradg
make clean
touch *.f
make lib

cd $RADSRC/matrices
make clean
touch *.f
make lib
