      program stitchseqtable
C     ****************************************************************
C     Program to stitch together several sequential access line data and
C     lco files, generated by Selecttempseqtopbuffloop.
C
C     Pat Irwin	14/5/18
C 
C     ****************************************************************
      implicit none
      character*256 buffer
      character*100 dirroot,namroot,seqfile,lcofile,opseqfil,oplcofil
      character*100 opname,rootname
      integer ntemp,nrange,irange,i,j,itemp
      integer i1,i2,j1,j2,ke,me,le,je
      integer jo,jd,jr,id,iso,nbin,lbin
      real vmin,vmax

      call prompt('Enter root name of output files : ')
      read(5,1)opname
1     format(a)

      do i = 1,len(opname)
       if(opname(i:i).ne.' ')jo=i
      enddo

      call prompt('Enter ID, ISO : ')
      read*,id,iso

      call prompt('Enter number of temperatures : ')
      read*,ntemp

      call prompt('Enter number of wavelength ranges : ')
      read*,nrange

      call prompt('Enter overall vmin, vmax : ')
      read*,vmin,vmax

      call prompt('Enter directory rootname : ')
      read(5,1)dirroot

      do i = 1,len(dirroot)
       if(dirroot(i:i).ne.' ')jd=i
      enddo

      call prompt('Enter individual file rootnames : ')
      read(5,1)rootname

      do i = 1,len(rootname)
       if(rootname(i:i).ne.' ')jr=i
      enddo

      do 1000 itemp=1,ntemp

       opname(jo+1:jo+2)='00'
       i1=int(itemp/10)
       i2=itemp-10*i1

       ke = jo+2
       me = ke-1
       opname(me:me)=char(i1+48)
       opname(ke:ke)=char(i2+48)

       call file(opname,opseqfil,'par')
       call file(opname,oplcofil,'lco')

       open(14,file=opseqfil,status='unknown')
       open(15,file=oplcofil,status='unknown')

       print*,'opseqfil',opseqfil
       print*,'oplcofil',oplcofil

       do 100 irange=0,nrange-1
         print*,'range = ',irange
         j1 = int(irange/10)
         j2 = irange-10*j1 
         if(irange.ge.10)then
          dirroot(jd+1:jd+2)='00'
          le=jd+2
          je=jd+1
          dirroot(je:je)=char(j1+48)
          dirroot(le:le)=char(j2+48)
         else 
          dirroot(jd+1:jd+1)='0'
          le=jd+1
          dirroot(le:le)=char(j2+48)
         endif

         seqfile=dirroot
         seqfile(le+1:le+1)='/'
         seqfile(le+2:le+2+jr-1)=rootname(1:jr)
         ke = le+2+jr+1
         me=ke-1
         seqfile(me:me)=char(i1+48)
         seqfile(ke:ke)=char(i2+48)

       

         call file(seqfile,seqfile,'par')
         call file(seqfile,lcofile,'lco')

         print*,'tmpseq:',seqfile
         print*,'tmplco:',lcofile

         open(13,file=lcofile,status='old',action='read')

         if(irange.eq.0)then
          read(13,1)buffer
          write(15,*)'VMIN, VMAX = ',vmin,vmax
          do i=1,2
           read(13,1)buffer
           write(15,1)buffer(1:120)
          enddo
          read(13,1)buffer
          write(15,*)'ID, ISO = ',id,iso
          read(13,1)buffer
          print*,buffer
          print*,buffer(9:)
          read(buffer(9:),*)lbin
          nbin=lbin*nrange
          write(15,*)'NBIN = ',nbin

         else
          do i=1,5
           read(13,1)buffer
          enddo
         endif

101      read(13,1,end=998)buffer
         write(15,1)buffer(1:120)
         goto 101
998      continue
         close(13)

         open(12,file=seqfile,status='old',action='read')
102      read(12,1)buffer
         if(buffer(2:2).eq.'#')then
          if(irange.eq.0)then
           print*,itemp,irange
           write(14,1)buffer(1:160)
           write(6,1)buffer(1:160) 
          endif
          goto 102
         endif

         write(14,1)buffer(1:160)
103      read(12,1,end=999)buffer
         write(14,1)buffer(1:160)
         goto 103

999      continue
         close(12)

100    continue 

       close(14)
       close(15)

1000  continue

      end
